development:
  secret_key_base: be3e0d5eb540297bf692038ed35d33083eaef7b4fb228a9363181bee04ce14e0008984844ebe98800bf3b6646674a506a9dc1abe999df7cfa56933dbb41068f3
  api_token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJ1c2VyIjp7ImlkIjo2NjE0MCwiZW1haWwiOiJwaXBlZnlkZXZyZWNydWl0aW5nZmFrZXVzZXJAbWFpbGluYXRvci5jb20iLCJhcHBsaWNhdGlvbiI6NDUzOH19.uUX4KIR4m_K-8NwLYhtVpsNnLEoLARebIQiyQDxEm3RZLHCffLrcH-V8RmuJLu8nqE8AQ-SvqUvgz3fe0UyZ4w
  organization_id: 92858
test:
  secret_key_base: abababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababab
  organization_id: 123
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  api_token: <%= ENV["API_TOKEN"] %>
  organization_id: <%= ENV["ORGANIZATION_ID"] %>
